# Generated by Django 3.1.4 on 2020-12-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PitzzaExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price to put on one slice')),
            ],
        ),
        migrations.CreateModel(
            name='PitzzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='size')),
                ('piecesNum', models.IntegerField(verbose_name='number of pieces')),
                ('price', models.FloatField(verbose_name='cost for pitzza without extras')),
            ],
        ),
    ]
