# Generated by Django 3.1.4 on 2020-12-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pitzza', '0002_auto_20201210_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitzzathrough',
            old_name='pExtras',
            new_name='pitzzaExtra',
        ),
    ]
